### ISSUE TITLE
"Rollup" Dependency has problem vite build error

### ISSUE THREAD

**Issue by Baldur404** [JeanJPNM/mindustry-schematic-parser#23]
log:
``` 
vite build
vite v4.5.0 building for production...
[plugin:vite:resolve] Module "url" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/mindustry-schematic-parser/dist/index.mjs". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:path" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/pkg-dir/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:path" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/find-up/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:url" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/find-up/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:process" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/locate-path/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:path" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/locate-path/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:fs" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/locate-path/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:url" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/locate-path/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "node:fs" has been externalized for browser compatibility, imported by "/Users/wangjingyue/WebstormProjects/blueprint/node_modules/path-exists/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 1489 modules transformed.
✓ built in 1.76s
"fileURLToPath" is not exported by "__vite-browser-external", imported by "node_modules/locate-path/index.js".
file: /Users/wangjingyue/WebstormProjects/blueprint/node_modules/locate-path/index.js:4:8
2: import path from 'node:path';
3: import fs, {promises as fsPromises} from 'node:fs';
4: import {fileURLToPath} from 'node:url';
           ^
5: import pLocate from 'p-locate';
error during build:
RollupError: "fileURLToPath" is not exported by "__vite-browser-external", imported by "node_modules/locate-path/index.js".
    at error (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at ReturnValueScope.findVariable (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at ConditionalExpression.bind (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at ArrowFunctionExpression.bind (file:///Users/wangjingyue/WebstormProjects/blueprint/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
wangjingyue@HUAWEI-MateBook-9-Pro blueprint % 
```
I try to exclude `"mindustry-schematic-parser": "^4.3.0"`, can exclude `"node_modules/locate-path/"`directory
so may I guess possible this repo use `Rollup`version too low ?

**Comment by JeanJPNM** [comment]
Can you create a reproducible example? I'm not sure of how to reproduce this issue.

As you can see here, the parser only uses `fileURLToPath` in a dynamic import, which leads me to believe another package is causing this issue.

https://github.com/JeanJPNM/mindustry-schematic-parser/blob/cf279b39305bcd7d2d5de873cd3581f17f4b46a7/src/util/resolve_assets.ts#L16-L18

**Comment by Baldur404** [comment]
this is a new project also `npm install "mindustry-schematic-parser": "^4.3.0"`this dependency in addition
[ReproductionLink](https://github.com/Baldur404/mindustry-schematic-parser-import-error-reproduction)

<img width="1470" alt="image" src="https://github.com/JeanJPNM/mindustry-schematic-parser/assets/117364120/56139fcc-2ab0-4b7e-933d-f1c960a2ecce">
