### ISSUE TITLE
uh. issue?

### ISSUE THREAD

**Issue by bend-n** [JeanJPNM/mindustry-schematic-parser#9]
```
file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:3640
        return new StreamedDataReader(bytes.buffer);
                                            ^

TypeError: Cannot read properties of undefined (reading 'buffer')
    at Function.compressedData (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:3640:45)
    at Function.decode (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:3811:28)
    at Function.decode (file:///home/bendn/node_modules/mindustry-schematic-parser/dist/index.mjs:3928:28)
    at file:///home/bendn/blocks/schem_image/new.js:5:29
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v17.7.1
```

**Comment by JeanJPNM** [comment]
That's weird, the error comes from this fucntion:
https://github.com/JeanJPNM/mindustry-schematic-parser/blob/fab28d0e7bb5eb37d571a235c017062f87e89fe8/src/schematic/io.ts#L46-L51

And as you can see the package Pako should deflate the byte array and then the function would create a StreamedDataReader from the result.

So this is more likely an issue with the input you are giving to the parser, or an issue with the Pako package itself.
